---
- name: Change listener in pgpool.conf 
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'listen_addresses'
    line: listen_addresses = '*'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change port in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'port'
    line: port = 5432
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_hostname0 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_hostname0'
    line: backend_hostname0 = 'tst-db01'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_port0 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_port0'
    line: backend_port0 = 5433
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_data_directory0 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_data_directory0'
    line: backend_data_directory0 = '/postgresql/pg_data'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_application_name0 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_application_name0'
    line: backend_application_name0 = 'tst-db01'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_hostname1 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_hostname1'
    line: backend_hostname1 = 'tst-db02'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_port1 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_port1'
    line: backend_port1 = 5433
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_weight1 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_weight1'
    line: backend_weight1 = 1
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_data_directory1 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_data_directory1'
    line: backend_data_directory1 = '/postgresql/pg_data'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_flag1 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_flag1'
    line: backend_flag1 = 'ALLOW_TO_FAILOVER'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_application_name1 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_application_name1'
    line: backend_application_name1 = 'tst-db02'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_hostname2 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_hostname2'
    line: backend_hostname2 = 'tst-db03'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_port2 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_port2'
    line: backend_port2 = 5433
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_weight2 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_weight2'
    line: backend_weight2 = 1
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_data_directory2 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_data_directory2'
    line: backend_data_directory2 = '/postgresql/pg_data'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_flag2 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_flag2'
    line: backend_flag2 = 'ALLOW_TO_FAILOVER'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change backend_application_name2 in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'backend_application_name2'
    line: backend_application_name2 = 'tst-db03'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change enable_pool_hba in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'enable_pool_hba'
    line: enable_pool_hba = on
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change max_pool in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'max_pool'
    line: max_pool = 10
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change pid_file_name in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'pid_file_name'
    line: pid_file_name = '/var/run/pgpool/pgpool.pid'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change sr_check_user in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'sr_check_user'
    line: sr_check_user = 'pgpool'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change sr_check_password in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'sr_check_password'
    line: sr_check_password = 'pgpool'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change health_check_period in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'health_check_period'
    line: health_check_period = 5
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change health_check_timeout in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'health_check_timeout'
    line: health_check_timeout = 30
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change health_check_user in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'health_check_user'
    line: health_check_user = 'pgpool'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change health_check_password in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'health_check_password'
    line: health_check_password = 'pgpool'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change health_check_max_retries in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'health_check_max_retries'
    line: health_check_max_retries = 3
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change failover_command in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'failover_command'
    line: failover_command = '/etc/pgpool-II/failover.sh %d %h %p %D %m %H %M %P %r %R %N %S'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change follow_master_command in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'follow_master_command'
    line: follow_master_command = '/etc/pgpool-II/follow_master.sh %d %h %p %D %m %H %M %P %r %R'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change recovery_user in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'recovery_user'
    line: recovery_user = 'postgres'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change recovery_password in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'recovery_password'
    line: recovery_password = 'postgres'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change recovery_1st_stage_command in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'recovery_1st_stage_command'
    line: recovery_1st_stage_command = 'recovery_1st_stage_command'
    owner: postgres
    group: postgres
    mode: '0600'
    state: present

- name: Change use_watchdog in pgpool.conf
  lineinfile:
    path: /etc/pgpool-II/pgpool.conf
    regexp: 'use_watchdog'
    line: use_watchdog = on
    owner: postgres
    group: postgres
    mode: '0600'
    state: present
