---
- hosts: posqlpgpool_cluster
  become: yes
  roles:
    - { role: posqlpgpool_packages, tags: [ 'prerequisite' ] }
    - { role: posqlpgpool_filesystem, tags: [ 'prerequisite' ] }
    - { role: posqlpgpool_setting, tags: [ 'prerequisite' ] }

- hosts: master
  become: yes
  roles:
    - { role: posqlmaster_conf, tags: [ 'configuration' ] }
