---
- hosts: cluster
  become: yes
  roles:
    - { role: cluster_packages, tags: [ 'prerequisite' ] }
    - { role: cluster_postgis, tags: [ 'prerequisite' ] }
    - { role: cluster_filesystem, tags: [ 'prerequisite' ] }
    - { role: cluster_authorizations, tags: [ 'prerequisite' ] }
    - { role: cluster_setting, tags: [ 'prerequisite' ] }
    - { role: cluster_pgdata, tags: [ 'prerequisite' ] }
    - { role: cluster_postgresqlconf, tags: [ 'configuration' ] }
    - { role: cluster_pghbaconf, tags: [ 'configuration' ] }
    - { role: cluster_poolhbaconf, tags: [ 'configuration' ] }
    - { role: cluster_pgpoolconf, tags: [ 'configuration' ] }
    - { role: cluster_scripts, tags: [ 'configuration' ] }
    - { role: cluster_logging, tags: [ 'configuration' ] }
    - { role: cluster_pgservice, tags: [ 'configuration' ] }

- hosts: master
  become: yes
  roles:
    - { role: master_postgresqlroles, tags: [ 'configuration' ] }
    - { role: master_pgpoolconf, tags: [ 'hierarchies' ] }

- hosts: st_slave
  become: yes
  roles:
    - { role: st_slave_pgpoolconf, tags: [ 'hierarchies' ] }

- hosts: nd_slave
  become: yes
  roles:
    - { role: nd_slave_pgpoolconf, tags: [ 'hierarchies' ] }

- hosts: cluster
  become: yes
  roles:
    - { role: cluster_pgposqlstart, tags: [ 'beginning' ] }
