---
- hosts: posqlpgpool_cluster
  become: yes
  roles:
    - { role: cluster_packages, tags: [ 'prerequisite' ] }
    - { role: cluster_filesystem, tags: [ 'prerequisite' ] }
    - { role: cluster_setting, tags: [ 'prerequisite' ] }
    - { role: cluster_ssh-key, tags: [ 'prerequisite' ] }

- hosts: master
  become: yes
  roles:
    - { role: master_postgresqlconf, tags: [ 'configuration' ] }
    - { role: master_postgresqlroles, tags: [ 'configuration' ] }
    - { role: master_pghbaconf, tags: [ 'configuration' ] }
    