---
- name: Make sure PostgreSQL is started but disabled
  systemd:
    name: postgresql-11
    enabled: no
    state: started
  tags: configuration

- name: Create pgpool role
  postgresql_user:
    name: pgpool
    password: ""
    port: 5433
    role_attr_flags: LOGIN
    state: present
  tags: configuration

- name: Create repl role
  postgresql_user:
    name: repl
    password: ""
    port: 5433
    role_attr_flags: REPLICATION,LOGIN
    state: present
  tags: configuration

- name: Grant role pg_monitor to pgpool
  postgresql_membership:
    group: pg_monitor
    target_roles: pgpool
    state: present    