---
- name: Change listener in postgresql.conf 
  postgresql_set:
    name: listen_addresses
    value: '*'
  become: true
  become_user: postgres
  tags: configuration

- name: Change port in postgresql.conf
  postgresql_set:
    name: port
    value: '5433'
  become: true
  become_user: postgres
  tags: configuration

- name: Change wal_level in postgresql.conf
  postgresql_set:
    name: wal_level
    value: 'hot_standby'
  become: true
  become_user: postgres
  tags: configuration

- name: Change wal_log_hints in postgresql.conf
  postgresql_set:
    name: wal_log_hints
    value: 'on'
  become: true
  become_user: postgres
  tags: configuration

- name: Change archive_mode in postgresql.conf
  postgresql_set:
    name: archive_mode
    value: 'on'
  become: true
  become_user: postgres
  tags: configuration

- name: Change archive_command in postgresql.conf
  postgresql_set:
    name: archive_command
    value: 'cp -i "%p" "/postgresql/archive/%f"'
  become: true
  become_user: postgres
  tags: configuration

- name: Change max_wal_senders in postgresql.conf
  postgresql_set:
    name: max_wal_senders
    value: '10'
  become: true
  become_user: postgres
  tags: configuration

- name: Change hot_standby in postgresql.conf
  postgresql_set:
    name: hot_standby
    value: 'on'
  become: true
  become_user: postgres
  tags: configuration
