---
- name: Install epel repos
  yum:
    name: epel-release
    state: present
  tags: prerequisite

- name: Add repository for PostGIS
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  tags: prerequisite

- name: Install PostGIS server packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - postgis25_11.x86_64
    - postgis25_11-client.x86_64
    - postgis25_11-devel.x86_64
    - postgis25_11-gui.x86_64
    - postgis25_11-utils.x86_64
    - postgis25_11-docs.x86_64
    state: present
  tags: prerequisite

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: prerequisite
