---
- name: Install epel repos
  yum:
    name: epel-release
    state: present
  tags: prerequisite

- name: Add repository for PostGIS
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  tags: prerequisite

#- name: Install dependencies for PostGIS
#  yum:
#    name: "{{ packages }}"
#  vars:
#    packages:
#    - libdapserver.so.7
#    - libnetcdf.so.7
#    - libdap.so.17
#    - libCharLS.so.1
#    - hdf5
#    - libdapclient.so.6
#    - libfreexl.so.1
#    - libcfitsio.so.2
#    - libhdf5.so.8
#    - libgta.so.0
#    state: present
#  tags: prerequisite

- name: Install PostGIS server packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - postgis25_11.x86_64
    - postgis25_11-client.x86_64
    - postgis25_11-devel.x86_64
    - postgis25_11-gui.x86_64
    - postgis25_11-utils.x86_64
    - postgis25_11-docs.x86_64
    state: present
  tags: prerequisite

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: prerequisite
