---
- name: Copy failover.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/failover.sh
    dest: /etc/pgpool-II/failover.sh
    owner: postgres
    group: postgres
    mode: '0777'
    backup: yes

- name: Copy follow_master.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/follow_master.sh
    dest: /etc/pgpool-II/follow_master.sh
    owner: postgres
    group: postgres
    mode: '0777'
    backup: yes

- name: Copy recovery_1st_stage_command, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/recovery_1st_stage_command
    dest: /postgresql/pg_data/recovery_1st_stage_command
    owner: postgres
    group: postgres
    mode: '0777'
    backup: yes

- name: Copy pgpool_remote_start, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/pgpool_remote_start
    dest: /postgresql/pg_data/pgpool_remote_start
    owner: postgres
    group: postgres
    mode: '0777'
    backup: yes

- name: Copy aws-escalation.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/aws-escalation.sh
    dest: /usr/local/bin/aws-escalation.sh
    owner: root
    group: root
    mode: '0755'
    backup: yes

- name: Copy aws-de-escalation.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/aws-de-escalation.sh
    dest: /usr/local/bin/aws-de-escalation.sh
    owner: root
    group: root
    mode: '0755'
    backup: yes

- name: Copy route-{{ sec_net_int }}.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/route-netint2
    dest: /etc/sysconfig/network-scripts/route-{{ sec_net_int }}.sh
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy rule-{{ pri_net_int }}.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/rule-netint1
    dest: /etc/sysconfig/network-scripts/rule-{{ pri_net_int }}.sh
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy rule-{{ sec_net_int }}.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/rule-netint2
    dest: /etc/sysconfig/network-scripts/rule-{{ sec_net_int }}.sh
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy ifcfg-{{ sec_net_int }}.sh, backing up the original if it differs from the copied version
  copy:
    src: /home/centos/ansible-posqlpgpoolcl3/scripts/ifcfg-netint2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ sec_net_int }}.sh
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Insert 100 t1 entry in /usr/lib/systemd/system/pgpool.service
  lineinfile:
    path: /etc/iproute2/rt_tables
    line: '100 t1'

- name: Insert 101 t2 entry in /usr/lib/systemd/system/pgpool.service
  lineinfile:
    path: /etc/iproute2/rt_tables
    line: '101 t2'
